name: Build and Deploy Next.js App with PM2

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    name: Build and Deploy Next.js App
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Dependencies and Build
      - name: Install Dependencies and Build
        run: |
          npm ci --legacy-peer-deps
          npm run build
          ls -a
        

      # Step 3: Upload Build Files and Environment Variables to EC2
      - name: Deploy Build and Environment Variables to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: |
            .next  # Built Next.js files
            package.json
            package-lock.json
          target: "/home/${{ secrets.EC2_USER }}/nextjs-app"

      # Step 4: Start App with PM2 and Use Environment Variables
      - name: Start App with PM2 on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Navigating to the app directory..."
            cd /home/${{ secrets.EC2_USER }}/nextjs-app

            echo "Creating .env file from GitHub Secrets..."
            cat <<EOF > .env
            NEXT_PUBLIC_PRIVATE_KEY=${{ secrets.NEXT_PUBLIC_PRIVATE_KEY }}
            NEXT_PUBLIC_DEPLOY_ADDRESS=${{ secrets.NEXT_PUBLIC_DEPLOY_ADDRESS }}
            EOF

            echo "Installing dependencies with legacy peer deps..."
            npm ci --legacy-peer-deps

            echo "Installing PM2 globally..."
            npm install -g pm2

            echo "Starting the Next.js application with PM2..."
            pm2 start npm --name "nextjs-app" -- run start

            echo "Saving PM2 process list..."
            pm2 save

            echo "Deployment and app startup complete!"
